_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 430d9fc9-c092-48fc-9813-6f6ba1b63abb
name: build-tools-demo-github
mail: boris.smirnov@pantheon.io
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
